name: "Generate document"

on:
  push:
    branches: [main]

defaults:
  run:
    working-directory: .

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: main.pdf
      - name: Copy files to the test website with the AWS CLI
        run: |
          aws s3 cp main.pdf s3://${{ secrets.S3_BUCKET }}/Resume.pdf --endpoint-url "${{ secrets.S3_ENDPOINT }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.S3_REGION }}
