name: "Generate document"

on:
  push:
    branches: [main]

defaults:
  run:
    working-directory: .

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
      - name: Rename file 
        run: mkdir gen && cp main.pdf gen/Resume.pdf
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: gen/Resume.pdf
      - uses: shallwefootball/upload-s3-action@master
        name: Upload to S3
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'gen'
          destination_dir: ''
